### ISSUE TITLE
Stated Acceptance Criteria

### ISSUE THREAD

**Issue by akshatjhingan** [IntroToCode/CodeMates10_Fall22#12]
1.  All contributions must relate to the recipes posted by Dingmi.  
2.  If there are no flags raised during the review process, and each pull request is approved by at least 2 people, then pull request can be successfully merged.
3. A comment indicating disagreement will require 2 additional reviewers before pull request merged.
4. In case of strong disagreement after pull request merged, separate issue can be created in the issue tab.

## 👥 People to consult

@gebarn @Eliz226 @Felipe-Arrazola @Berkeleyway @nedivatara 
## 📃 Details

Text

**Comment by nedivatara** [comment]
So should we all do additional pull requests so that we can approve them then merge them?

**Comment by akshatjhingan** [comment]
Yes.

**Comment by Eliz226** [comment]
looks good to me, thanks for setting this up!

**Comment by Eliz226** [comment]
@Berkeleyway @Felipe-Arrazola  @gebarn please take a look - and we can close this one!

**Comment by Felipe-Arrazola** [comment]
I agree with the proposed changes

**Comment by Berkeleyway** [comment]
I approved those changes.

**Comment by gebarn** [comment]
I agree with the proposed changes!
