### ISSUE TITLE
Please merge my pull request

### ISSUE THREAD

**Issue by nedivatara** [IntroToCode/CodeMates10_Fall22#3]
## 💬 Discussion topic

Hi team, can someone merge my pull request into the main branch?

## ❗ Potential issues

Though it has been approved it has not been merged into the pull request.

## 👥 People to consult

@gebarn @Eliz226 @akshatjhingan @Berkeleyway @Felipe-Arrazola 

## 📃 Details

Click the button at the end of my pull request that says "merge pull request" to merge it into the main branch.
Thanks!

**Comment by akshatjhingan** [comment]
I just did.
